kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: cpu-stress
  # Uncomment this to pause the stress test
  # annotations:
    # experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - stress-test-cpu
  mode: fixed-percent
  value: '100'
  stressors:
    cpu:
      workers: 100
      load: 100
