apiVersion: v1
kind: Namespace
metadata:
  name: stress-test-cpu
  labels:
    name: stress-test-cpu
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: stress-test-cpu
  name: mem-cpu-demo
spec:
  hard:
    limits.cpu: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stress-test-cpu
  name: nginx-deployment-1
  labels:
    app: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx-1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stress-test-cpu
  name: nginx-deployment-2
  labels:
    app: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - name: nginx-2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 4
